/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  designSystem: [
    'design-system',
    'design-system/foundations',
    'design-system/figma',
    {
      type: 'category',
      label: 'Components',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'design-system/components',
        },
      ],
    },
  ],
  wordpress: [
    'wordpress',
    'wordpress/tasks',
    'wordpress/plugins',
  ]
};

module.exports = sidebars;
